Repository GrafVonTee/Interpol, pull requests merged in 2023-05, with the labels that each got.

#31 Added comments in `develop_input`
  src/user_interaction/ConsoleInteraction.cpp
  src/user_interaction/Parsing.cpp
Labels: documentation

#29 Develop math feature 1
  CMakeLists.txt
  include/CalculateIntersections.h
  include/ConsoleInteraction.h
  include/GeometryUtils.h
  include/Parsing.h
  include/StatesUtils.h
  src/CalculateIntersections.cpp
  src/main.cpp
  src/math/CalculateIntersections.cpp
  src/user_interaction/ConsoleInteraction.cpp
  src/user_interaction/Parsing.cpp
  src/user_interaction/Parsing.h
  src/utils/GeometryUtils.cpp
Labels: enhancement

#34 Create SECURITY.md
  SECURITY.md
Labels: documentation

#36 Develop grahics
  .github/workflows/ci.yml
  CMakeLists.txt
  include/CalculateIntersections.h
  include/ConsoleInteraction.h
  include/DrawImage.h
  include/GeometryUtils.h
  include/Parsing.h
  src/drawing/DrawImage.cpp
  src/main.cpp
  src/math/CalculateIntersections.cpp
  src/user_interaction/Parsing.cpp
  src/utils/GeometryUtils.cpp
  tests/unit_tests.cpp
Labels: enhancement

#45 Develop full main compilation
  CMakeLists.txt
  SECURITY.md
  include/CalculateIntersections.h
  include/ConsoleInteraction.h
  include/GetImVecFromPolygon.h
  src/drawing/GetImVecFromPolygon.cpp
  src/main.cpp
  src/math/CalculateIntersections.cpp
  src/user_interaction/ConsoleInteraction.cpp
Labels: enhancement

#46 Update SECURITY.md
  SECURITY.md
Labels: documentation

#47 Develop scale drawing
  CMakeLists.txt
  include/GetImVecFromPolygon.h
  src/drawing/DrawImage.cpp
  src/drawing/GetImVecFromPolygon.cpp
  src/main.cpp
Labels: enhancement, help wanted

#48 Another one PR
  include/GeometryUtils.h
  include/GetImVecFromPolygon.h
  src/drawing/GetImVecFromPolygon.cpp
Labels: documentation, enhancement

#52 Drawing Refactor
  CMakeLists.txt
  include/ConstantsForDrawing.h
  include/DrawImage.h
  include/GetImVecFromPolygon.h
  src/drawing/DrawImage.cpp
  src/drawing/GetImVecFromPolygon.cpp
  src/main.cpp
  src/utils/ConstantsForDrawing.cpp
Labels: enhancement

#54 Try to fix codeeql
  .github/workflows/codeql.yml
Labels: bug

#58 Update README.md
  README.md
Labels: documentation

#61 Polygon patch geometry
  CONTRIBUTING.md
  SECURITY.md
  include/GeometryUtils.h
  include/StatesUtils.h
  src/utils/GeometryUtils.cpp
  tests/unit_tests.cpp
Labels: bug, enhancement

#63 Kudasov's report
  reports/Example (dd.mm.yyyy -- dd.mm.yyyy).md
  reports/Maxim Kudasov (20.04.2023 -- 20.05.2023).md
Labels: documentation, question

#76 Update SECURITY.md
  SECURITY.md
Labels: bug, documentation

#73 Create report Krasilnikov
  CONTRIBUTING.md
  reports/Krasilnikov Nikolay (20.04.2023 -- 20.05.2023).md
Labels: documentation, question

#79 Added nice functional
  CMakeLists.txt
  include/GetImVecFromPolygon.h
  src/drawing/DrawImage.cpp
  src/drawing/GetImVecFromPolygon.cpp
  src/main.cpp
Labels: enhancement

#81 Update README.md
  README.md
Labels: documentation, bugfix

#96 add buttons
  include/DrawImage.h
  src/drawing/DrawImage.cpp
Labels: enhancement

#94 Final refactor
  include/ConstantsForDrawing.h
  include/GeometryUtils.h
  src/utils/GeometryUtils.cpp
Labels: enhancement

#95 Develop alxyll
  include/ConsoleInteraction.h
  src/drawing/DrawImage.cpp
  src/main.cpp
  src/user_interaction/ConsoleInteraction.cpp
Labels: enhancement, bugfix

#98 Add flags check and sort for emplaceBack()
  include/GeometryUtils.h
  src/utils/GeometryUtils.cpp
Labels: enhancement, bugfix

#97 Develop resolve conflict alxyll
  include/CalculateIntersections.h
  include/ConsoleInteraction.h
  include/StatesUtils.h
  src/drawing/DrawImage.cpp
  src/main.cpp
  src/math/CalculateIntersections.cpp
  src/user_interaction/ConsoleInteraction.cpp
  src/utils/GeometryUtils.cpp
  tests/unit_tests.cpp
Labels: enhancement
