Repository GrafVonTee/Interpol, pull requests merged in 2023-06, with the labels that each got.

#100 Develop singleton
  include/ConsoleInteraction.h
  include/DrawImage.h
  include/StatesLibrary.h
  src/drawing/DrawImage.cpp
  src/main.cpp
  src/user_interaction/ConsoleInteraction.cpp
  src/utils/StatesLibrary.cpp
Labels: enhancement

#102 History reinforced
  include/DrawImage.h
  include/StatesLibrary.h
  include/StatesUtils.h
  src/drawing/DrawImage.cpp
  src/main.cpp
  src/user_interaction/ConsoleInteraction.cpp
  src/utils/StatesLibrary.cpp
Labels: enhancement, bugfix

#103 Create Example360.md
  reports/Example360.md
Labels: documentation

#99 Develop new g UI
  CMakeLists.txt
  include/CalculateIntersections.h
  include/ConsoleInteraction.h
  include/ConstantsForDrawing.h
  include/DrawImage.h
  include/GeometryUtils.h
  include/GetImVecFromPolygon.h
  include/Parsing.h
  include/StatesLibrary.h
  include/StatesUtils.h
  src/drawing/DrawImage.cpp
  src/drawing/GetImVecFromPolygon.cpp
  src/main.cpp
  src/math/CalculateIntersections.cpp
  src/user_interaction/ConsoleInteraction.cpp
  src/user_interaction/Parsing.cpp
  src/utils/ConstantsForDrawing.cpp
  src/utils/GeometryUtils.cpp
  src/utils/StatesLibrary.cpp
  tests/ConsoleInteractionTests.cpp
  tests/ImgVecTests.cpp
  tests/IntersectionTests.cpp
  tests/MathTests.cpp
  tests/ParserTests.cpp
  tests/PointTests.cpp
  tests/PolygonTests.cpp
  tests/StateLibraryTests.cpp
  tests/unit_tests.cpp
Labels: bug, enhancement

#106 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#110 Conflict branch into develop
  .github/workflows/main.yml
  CONTRIBUTING.md
  README.md
  SECURITY.md
  include/ConstantsForDrawing.h
  include/GeometryUtils.h
  include/GetImVecFromPolygon.h
  reports/Alexandr Yulin (20.04.2023 - 20.05.2023).md
  reports/EremenkoDT.md
  reports/Example (dd.mm.yyyy -- dd.mm.yyyy).md
  reports/Example360.md
  reports/Krasilnikov Nikolay (20.04.2023 -- 20.05.2023).md
  reports/KuznetsovIlya.md
  reports/Maxim Kudasov (20.04.2023 -- 20.05.2023).md
  src/drawing/DrawImage.cpp
  src/drawing/GetImVecFromPolygon.cpp
  src/main.cpp
  src/user_interaction/ConsoleInteraction.cpp
  src/utils/ConstantsForDrawing.cpp
Labels: bugfix

#112 Create Kuznetsov Ilya 360.md
  reports/Kuznetsov Ilya (20.04.2023-20.05.2023).md
  reports/Kuznetsov360.md
Labels: help wanted, Report

#113 Docs update
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  README.md
  third-party-programs.txt
Labels: documentation

#111 360review kudasov
  reports/Example360.md
  reports/Kudasov360.md
Labels: help wanted, Report

#116 new window name
  CMakeLists.txt
  src/drawing/DrawImage.cpp
Labels: bugfix

#115 360report
  reports/Eremenko360.md
Labels: Report

#117 Create Krasilnikov360.md
  reports/Krasilnikov360.md
Labels: Report

#118 Updated readme
  CONTRIBUTING.md
  README.md
Labels: documentation, bugfix

#109 Huge update
  CMakeLists.txt
  CONTRIBUTING.md
  README.md
  include/CalculateIntersections.h
  include/ConsoleInteraction.h
  include/ConstantsForDrawing.h
  include/DrawImage.h
  include/GeometryUtils.h
  include/GetImVecFromPolygon.h
  include/Parsing.h
  include/StatesLibrary.h
  include/StatesUtils.h
  src/drawing/DrawImage.cpp
  src/drawing/GetImVecFromPolygon.cpp
  src/main.cpp
  src/math/CalculateIntersections.cpp
  src/user_interaction/ConsoleInteraction.cpp
  src/user_interaction/Parsing.cpp
  src/utils/ConstantsForDrawing.cpp
  src/utils/GeometryUtils.cpp
  src/utils/StatesLibrary.cpp
  tests/ConsoleInteractionTests.cpp
  tests/ImgVecTests.cpp
  tests/IntersectionTests.cpp
  tests/MathTests.cpp
  tests/ParserTests.cpp
  tests/PointTests.cpp
  tests/PolygonTests.cpp
  tests/StateLibraryTests.cpp
  tests/unit_tests.cpp
Labels: enhancement, New Stable Version

#120 fix gitignore
  .gitignore
Labels: bugfix

#121 Develop
  .github/workflows/main.yml
  .gitignore
  CMakeLists.txt
Labels: bugfix, New Stable Version
